create table profile (
    id bigint generated by default as identity primary key,
    nickname varchar(64) not null,
    account varchar(64) not null unique,
    avatar varchar(512),
    bio varchar(512),
    role varchar(128),
    location varchar(128),
    followers int not null default 0
);

create table profile_skill (
    id bigint generated by default as identity primary key,
    profile_id bigint not null,
    skill varchar(64) not null,
    sort_order int not null default 0
);

create table profile_link (
    id bigint generated by default as identity primary key,
    profile_id bigint not null,
    label varchar(64) not null,
    url varchar(512) not null,
    sort_order int not null default 0
);

create table "user" (
    id bigint generated by default as identity primary key,
    phone varchar(11) not null unique,
    password varchar(100) not null,
    create_time timestamp not null default current_timestamp,
    profile_id bigint not null,
    role varchar(32) not null default 'USER'
);

create table tag (
    id bigint generated by default as identity primary key,
    name varchar(64) not null,
    sort_order int not null default 0
);

create table article (
    id bigint generated by default as identity primary key,
    title varchar(160) not null,
    summary varchar(512) not null,
    cover varchar(512),
    category varchar(64) not null,
    content clob,
    status varchar(32) not null default 'PENDING_REVIEW',
    author_user_id bigint not null,
    review_time timestamp,
    reviewer_user_id bigint,
    reject_reason varchar(512),
    deleted boolean not null default false,
    deleted_at timestamp,
    deleted_by bigint,
    published_at date not null,
    updated_at date not null,
    views int not null default 0,
    likes int not null default 0,
    comments int not null default 0
);

create table article_review_record (
    id bigint generated by default as identity primary key,
    article_id bigint not null,
    reviewer_user_id bigint not null,
    before_status varchar(32) not null,
    after_status varchar(32) not null,
    approved boolean not null,
    reject_reason varchar(512),
    review_time timestamp not null default current_timestamp
);

create table article_like (
    article_id bigint not null,
    user_id bigint not null,
    created_at timestamp not null default current_timestamp,
    primary key (article_id, user_id)
);

create table article_comment (
    id bigint generated by default as identity primary key,
    article_id bigint not null,
    user_id bigint not null,
    root_comment_id bigint,
    reply_to_comment_id bigint,
    content varchar(1000) not null,
    created_at timestamp not null default current_timestamp
);

create table article_tag (
    article_id bigint not null,
    tag_id bigint not null,
    primary key (article_id, tag_id)
);

create table question (
    id bigint generated by default as identity primary key,
    title varchar(160) not null,
    description varchar(512) not null,
    answer_count int not null default 0,
    updated_at date not null
);

create table question_tag (
    question_id bigint not null,
    tag_id bigint not null,
    primary key (question_id, tag_id)
);
